package com.hatchwatch.app.ui

object HwCopy {
    private val en = mapOf(
        "setup.kicker" to "Gen 1 companion",
        "setup.blurb" to "Log the hatch, pick who you want, and we track hearts, discipline, and the 15-minute care window so the device never beats you.",
        "setup.step1" to "1 Character",
        "setup.step2" to "2 Hatch",
        "setup.step3" to "3 Confirm",
        "setup.who" to "Who are you raising?",
        "setup.continue" to "Continue",
        "setup.back" to "Back",
        "setup.when" to "When did this life start?",
        "setup.hatched" to "It just hatched",
        "setup.hatched.d" to "Baby is out. Both meters start empty — feed immediately.",
        "setup.clock" to "I just set the clock",
        "setup.clock.d" to "Egg hatches in about 5 minutes.",
        "setup.custom" to "I know the exact time",
        "setup.custom.d" to "Use this if the run already started. Then match hearts on the home screen.",
        "setup.pick" to "Pick date and time",
        "setup.nick" to "Nickname",
        "setup.nick.ph" to "My P1",
        "setup.shellLang" to "Shell language",
        "setup.shell.en" to "English (Bill)",
        "setup.shell.jp" to "Japanese (Oyajitchi)",
        "setup.fw" to "Which P1",
        "setup.fw.replica" to "2018 replica",
        "setup.fw.vintage" to "1996–97 original",
        "setup.fw.d" to "Replica keeps calling after 100% discipline — a miss is a discipline mistake. Original stops at 100%, and skipping a scold does not add a miss.",
        "setup.start" to "Start watching",
        "setup.demo" to "Preview a Marutchi run",
        "nav.home" to "Home",
        "nav.plan" to "Plan",
        "nav.log" to "Log",
        "nav.guide" to "Guide",
        "act.meal" to "Meal",
        "act.snack" to "Snack",
        "act.game" to "Game",
        "act.clean" to "Clean",
        "act.scold" to "Scold",
        "act.medicine" to "Heal",
        "act.lights" to "Lights off",
        "act.miss" to "Missed",
        "care.next" to "Next care",
        "care.clear" to "All clear",
        "care.clear.d" to "No call window is open. Hearts drain while it is awake.",
        "care.now" to "Do this now",
        "care.soon" to "Upcoming",
        "care.overdue" to "Overdue",
        "care.check" to "Check the shell",
        "care.onShell" to "On the shell",
        "care.notOnShell" to "Not on the shell",
        "home.undo" to "Undo last",
        "home.match" to "Match device",
        "home.settings" to "Settings",
        "home.nextHunger" to "Next hunger",
        "home.nextHappy" to "Next happy",
        "home.nextPoop" to "Next poop",
        "home.nextSick" to "Next skull",
        "home.nextDisc" to "Attention",
        "home.discDrops" to "in {n} heart drops",
        "home.discNow" to "Look now",
        "home.discNone" to "None this form",
        "home.sleep" to "Sleep",
        "home.evo" to "Evolution",
        "home.empty" to "Empty",
        "home.asleep" to "Asleep",
        "home.naps" to "Naps",
        "home.wakes" to "Wakes {d}",
        "home.missCare" to "Care mistake",
        "home.missDisc" to "Discipline miss",
        "lcd.hungry" to "Hungry",
        "lcd.happy" to "Happy",
        "lcd.disc" to "Disc",
        "lcd.attn" to "Attention",
        "lcd.sick" to "Sick",
        "lcd.night" to "Night",
        "lcd.lights" to "Lights",
        "lcd.awake" to "Awake",
        "lcd.on" to "Lights on",
        "lcd.off" to "Lights off",
        "path.title" to "Growth path",
        "path.hit" to "On target",
        "path.path" to "On path",
        "path.off" to "Off path",
        "path.aim" to "Aiming for {name}",
        "path.heading" to " → heading {name}",
        "path.grew" to "This is {name}",
        "path.wanted" to "Wanted {name}",
        "path.grown" to "Adult form is set",
        "path.care" to "Care mistakes",
        "path.disc" to "Disc. mistakes",
        "path.scold" to "When it misbehaves: scold",
        "path.ignore" to "When it misbehaves: let it timeout",
        "path.either" to "When it misbehaves: either is fine",
        "budget.grown" to "Grown as {name}. Care mistakes {care}. Discipline {disc}.",
        "budget.grownOff" to "Grown as {name} (wanted {target}). Care mistakes {care}. Discipline {disc}.",
        "sync.title" to "Match the device",
        "sync.lead" to "Copy the status screens from the shell.",
        "sync.form" to "Form",
        "sync.hunger" to "Hunger",
        "sync.happy" to "Happy",
        "sync.disc" to "Discipline %",
        "sync.weight" to "Weight",
        "sync.care" to "Care mistakes",
        "sync.dmiss" to "Disc. mistakes",
        "sync.poop" to "Poop",
        "sync.age" to "Age",
        "sync.skull" to "Skull icon is showing",
        "sync.attn" to "Attention light is on",
        "sync.evo" to "Shell just evolved — restart this stage",
        "sync.cancel" to "Cancel",
        "sync.save" to "Save match",
        "set.title" to "Settings",
        "set.sound" to "Sound",
        "set.alerts" to "Alerts",
        "set.backup" to "Backup",
        "set.backup.d" to "Same JSON as the website. Save a file here, Open file there — or the other way around.",
        "set.saveFile" to "Save file",
        "set.openFile" to "Open file",
        "set.copy" to "Copy short",
        "set.paste" to "Paste backup",
        "set.restored" to "Restored",
        "set.cutoff" to "That backup looks cut off. Save a file instead of pasting a long log.",
        "set.bad" to "Could not read that backup.",
        "set.copied" to "Copied {n} characters",
        "set.end" to "End run",
        "set.end.q" to "End this run? Logs will be cleared.",
        "set.close" to "Close",
        "set.fw" to "Which P1",
        "theme.title" to "Shell",
        "theme.lead" to "Match the plastic. The LCD stays the same.",
        "theme.classic" to "Classic replica shells (1997–98)",
        "theme.modern" to "Modern & rerelease",
        "theme.pink-yellow" to "Pink with Yellow",
        "theme.white-blue" to "White with Blue",
        "theme.purple-pink" to "Purple with Pink",
        "theme.white-red" to "White with Red",
        "theme.yellow-black" to "Yellow with Black",
        "theme.black-carbon" to "Solid Black / Carbon",
        "theme.candy-swirl" to "Candy Swirl",
        "theme.neon-pop" to "Neon Lights",
        "theme.argyle-heart" to "Argyle Heart",
        "theme.flower-perfume" to "Flower Perfume",
        "theme.tama-garden" to "Tama Garden",
        "theme.gingham-avocado" to "Gingham Avocado",
        "theme.pastel-checkers" to "Pastel Candy & Checkers",
        "theme.diner" to "Fast Food / Diner",
        "theme.paper-collage" to "Paper Collage",
        "theme.space-astronaut" to "Space Astronaut",
        "lang.en" to "English",
        "lang.uk" to "Українська",
        "log.title" to "Care log",
        "log.empty" to "Nothing logged yet.",
        "plan.kicker" to "Target",
        "plan.how" to "How to hit it",
        "plan.grewOff" to "This run grew {name}. The {target} plan is closed — care the adult you have.",
        "guide.title" to "Field guide",
        "guide.lead" to "Heart loss, sleep, and shots from P1 ROM notes. Stage lengths are the observed 1996 times.",
        "guide.rule" to "The 15-minute rule",
        "guide.r1" to "Attention lights for hunger, happy, or lights-on-at-sleep. Respond within 15 minutes or it is a care mistake.",
        "guide.r2" to "Misbehave is after a set number of heart drops while both meters still have hearts — not random.",
        "guide.r3" to "Poop and sickness do not beep on the shell. Hatchwatch chirps when the timer is due.",
        "guide.r4" to "Hearts only drain while awake.",
        "guide.r5" to "Pause the shell with A+C until SET if you cannot tend a window.",
        "guide.r6" to "Each form gets one scheduled skull (ROM timer, not dice), plus four poops, plus too many snacks on a replica.",
    )

    private val uk = mapOf(
        "setup.kicker" to "Компаньйон Gen 1",
        "setup.blurb" to "Запиши вилуплення, обери кого ростиш — ми стежимо за серцями, дисципліною і 15-хвилинним вікном.",
        "setup.step1" to "1 Персонаж",
        "setup.step2" to "2 Вилуплення",
        "setup.step3" to "3 Підтвердити",
        "setup.who" to "Кого вирощуєш?",
        "setup.continue" to "Далі",
        "setup.back" to "Назад",
        "setup.when" to "Коли почалося це життя?",
        "setup.hatched" to "Щойно вилупилось",
        "setup.hatched.d" to "Малюк уже є. Обидва лічильники порожні — годуй одразу.",
        "setup.clock" to "Щойно поставив годинник",
        "setup.clock.d" to "Яйце вилупиться приблизно за 5 хвилин.",
        "setup.custom" to "Знаю точний час",
        "setup.custom.d" to "Якщо забіг уже йде. Потім піджени серця на головному екрані.",
        "setup.pick" to "Обрати дату і час",
        "setup.nick" to "Ім’я",
        "setup.nick.ph" to "Мій P1",
        "setup.shellLang" to "Мова корпуса",
        "setup.shell.en" to "English (Bill)",
        "setup.shell.jp" to "Японська (Oyajitchi)",
        "setup.fw" to "Який P1",
        "setup.fw.replica" to "Репліка 2018",
        "setup.fw.vintage" to "Оригінал 1996–97",
        "setup.fw.d" to "Репліка кличе й після 100% дисципліни — промах це помилка дисципліни. Оригінал зупиняється на 100%.",
        "setup.start" to "Почати стежити",
        "setup.demo" to "Переглянути забіг Marutchi",
        "nav.home" to "Дім",
        "nav.plan" to "План",
        "nav.log" to "Журнал",
        "nav.guide" to "Довідник",
        "act.meal" to "Обід",
        "act.snack" to "Ласощі",
        "act.game" to "Гра",
        "act.clean" to "Прибрати",
        "act.scold" to "Сварити",
        "act.medicine" to "Ліки",
        "act.lights" to "Світло вимк.",
        "act.miss" to "Промах",
        "care.next" to "Наступний догляд",
        "care.clear" to "Усе спокійно",
        "care.clear.d" to "Вікно виклику закрите. Серця падають, поки воно не спить.",
        "care.now" to "Зроби зараз",
        "care.soon" to "Скоро",
        "care.overdue" to "Прострочено",
        "care.check" to "Перевір корпус",
        "care.onShell" to "Є на корпусі",
        "care.notOnShell" to "Немає на корпусі",
        "home.undo" to "Скасувати",
        "home.match" to "Підігнати корпус",
        "home.settings" to "Налаштування",
        "home.nextHunger" to "Наступний голод",
        "home.nextHappy" to "Наступне щастя",
        "home.nextPoop" to "Наступна какашка",
        "home.nextSick" to "Наступний череп",
        "home.nextDisc" to "Увага",
        "home.discDrops" to "за {n} падінь сердець",
        "home.discNow" to "Дивись зараз",
        "home.discNone" to "Немає в цій формі",
        "home.sleep" to "Сон",
        "home.evo" to "Еволюція",
        "home.empty" to "Порожньо",
        "home.asleep" to "Спить",
        "home.naps" to "Дрімає",
        "home.wakes" to "Прокинеться {d}",
        "home.missCare" to "Помилка догляду",
        "home.missDisc" to "Промах дисципліни",
        "lcd.hungry" to "Голод",
        "lcd.happy" to "Щастя",
        "lcd.disc" to "Дисц",
        "lcd.attn" to "Увага",
        "lcd.sick" to "Хворіє",
        "lcd.night" to "Ніч",
        "lcd.lights" to "Світло",
        "lcd.awake" to "Не спить",
        "lcd.on" to "Світло ввімк",
        "lcd.off" to "Світло вимк",
        "path.title" to "Шлях росту",
        "path.hit" to "У цілі",
        "path.path" to "На шляху",
        "path.off" to "Збилось",
        "path.aim" to "Ціль {name}",
        "path.heading" to " → йде на {name}",
        "path.grew" to "Це {name}",
        "path.wanted" to "Ціль була {name}",
        "path.grown" to "Форма дорослого зафіксована",
        "path.care" to "Помилки догляду",
        "path.disc" to "Промахи дисц.",
        "path.scold" to "Коли пустує: сварити",
        "path.ignore" to "Коли пустує: хай вигорить",
        "path.either" to "Коли пустує: будь-як",
        "budget.grown" to "Виріс як {name}. Догляд {care}. Дисципліна {disc}.",
        "budget.grownOff" to "Виріс як {name} (ціль була {target}). Догляд {care}. Дисципліна {disc}.",
        "sync.title" to "Підігнати корпус",
        "sync.lead" to "Скопіюй екрани статусу з корпуса.",
        "sync.form" to "Форма",
        "sync.hunger" to "Голод",
        "sync.happy" to "Щастя",
        "sync.disc" to "Дисципліна %",
        "sync.weight" to "Вага",
        "sync.care" to "Помилки догляду",
        "sync.dmiss" to "Промахи дисц.",
        "sync.poop" to "Какашки",
        "sync.age" to "Вік",
        "sync.skull" to "Горить череп",
        "sync.attn" to "Горить увага",
        "sync.evo" to "Корпус щойно еволюціонував",
        "sync.cancel" to "Скасувати",
        "sync.save" to "Зберегти",
        "set.title" to "Налаштування",
        "set.sound" to "Звук",
        "set.alerts" to "Сповіщення",
        "set.backup" to "Резервна копія",
        "set.backup.d" to "Той самий JSON, що й на сайті. Збережи файл тут, відкрий там — або навпаки.",
        "set.saveFile" to "Зберегти файл",
        "set.openFile" to "Відкрити файл",
        "set.copy" to "Копіювати коротке",
        "set.paste" to "Вставити копію",
        "set.restored" to "Відновлено",
        "set.cutoff" to "Копія обрізана. Збережи файл замість довгої вставки.",
        "set.bad" to "Не вдалося прочитати цю копію.",
        "set.copied" to "Скопійовано {n} символів",
        "set.end" to "Завершити забіг",
        "set.end.q" to "Завершити забіг? Журнал буде стерто.",
        "set.close" to "Закрити",
        "set.fw" to "Який P1",
        "theme.title" to "Корпус",
        "theme.lead" to "Під колір пластику. LCD лишається той самий.",
        "theme.classic" to "Класичні репліки (1997–98)",
        "theme.modern" to "Сучасні й перевипуски",
        "theme.pink-yellow" to "Рожевий із жовтим",
        "theme.white-blue" to "Білий із синім",
        "theme.purple-pink" to "Фіолетовий із рожевим",
        "theme.white-red" to "Білий із червоним",
        "theme.yellow-black" to "Жовтий із чорним",
        "theme.black-carbon" to "Чорний / карбон",
        "theme.candy-swirl" to "Цукровий вихор",
        "theme.neon-pop" to "Неон",
        "theme.argyle-heart" to "Арґайл із серцями",
        "theme.flower-perfume" to "Квіткові парфуми",
        "theme.tama-garden" to "Сад Tama",
        "theme.gingham-avocado" to "Авокадо в клітинку",
        "theme.pastel-checkers" to "Пастельні цукерки",
        "theme.diner" to "Закусочна",
        "theme.paper-collage" to "Паперовий колаж",
        "theme.space-astronaut" to "Космонавт",
        "lang.en" to "English",
        "lang.uk" to "Українська",
        "log.title" to "Журнал догляду",
        "log.empty" to "Ще нічого немає.",
        "plan.kicker" to "Ціль",
        "plan.how" to "Як влучити",
        "plan.grewOff" to "Цей забіг виріс у {name}. План {target} закритий — доглядай цього дорослого.",
        "guide.title" to "Довідник",
        "guide.lead" to "Втрата сердець, сон і уколи з нотаток ROM P1.",
        "guide.rule" to "Правило 15 хвилин",
        "guide.r1" to "Увага горить на голод, щастя або світло під час сну. 15 хвилин — і помилка догляду.",
        "guide.r2" to "Пустощі після певної кількості падінь сердець, поки обидва лічильники не порожні — не випадково.",
        "guide.r3" to "Какашки і хвороба не пищать на корпусі. Hatchwatch пищить, коли таймер вийшов.",
        "guide.r4" to "Серця падають лише не сплячи.",
        "guide.r5" to "Пауза корпуса A+C до SET, якщо не можеш встигнути.",
        "guide.r6" to "Кожна форма має один запланований череп, плюс чотири какашки, плюс забагато ласощів на репліці.",
    )

    fun t(locale: String, key: String, vars: Map<String, String> = emptyMap()): String {
        val raw = (if (locale == "uk") uk else en)[key] ?: en[key] ?: key
        return vars.entries.fold(raw) { acc, (k, v) -> acc.replace("{$k}", v) }
    }
}
